name: flutter_toolbox
description: Common flutter widgets and helper methods.
version: 5.6.2
homepage: https://github.com/humazed/flutter_toolbox

# flutter packages pub run build_runner watch --delete-conflicting-outputs
# flutter pub pub publish --dry-run
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  intl_translation: ^0.17.9
  async: ^2.4.2

  stack_trace: ^1.9.5
  provider: ^4.3.2+1
  oktoast: ^2.3.2
  flushbar: ^1.10.4
  shared_preferences: ^0.5.10
  image_picker: ^0.6.7+7
  flutter_image_compress: ^0.7.0
  cached_network_image: ^2.3.1
  flutter_cache_manager: ^1.4.1
  photo_view: ^0.10.2
  connectivity: ^0.4.9+2
  url_launcher: ^5.5.2
  uuid: ^2.2.2
  path_provider: ^1.6.14
  path: ^1.7.0

  http: ^0.12.2
  json_annotation: ^3.0.1
  chopper2: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1

  json_serializable:
    #    path: D:\AS\ASP\Prod\OpenSource\json_serializable\json_serializable
    git:
      url: git://github.com/humazed/json_serializable.git
      path: json_serializable

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.github.humazed.flutter_toolbox
    pluginClass: FlutterToolboxPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
